service:
  name: serverless-ssr-react-lambda-at-edge

frameworkVersion: ">=1.6.0 <2.0.0"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: us-east-1 # Lambda@Edge functions have to be in US East 1

custom:
  BUCKET_ORIGIN: http://<your-bucket>.s3-website.<your-region>.amazonaws.com
  webpack:
    webpackConfig: "webpack.server.js"
    includeModules: true

functions:
  ssr:
    handler: server/server.handler
    description: Render site
    events:
      - cloudFront:
          eventType: origin-request
          pathPattern: /*
          origin: ${self:custom.BUCKET_ORIGIN}
